# Generated by Django 4.1.6 on 2023-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profiles_paired_with_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Paired_with_ID',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
