# Generated by Django 4.1.6 on 2023-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Paired_with_ID',
            field=models.IntegerField(default=None),
        ),
    ]
